# Generated by Django 4.1 on 2022-08-23 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Yoshi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Aktyorlar va rejissorlar',
                'verbose_name_plural': 'Aktyorlar va rejissorlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tevsifi')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tevsifi')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('tagline', models.CharField(default='', max_length=100, verbose_name='Qisqacha tavsif')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='Poster')),
                ('year', models.PositiveSmallIntegerField(default=2019, verbose_name='Chiqarilgan yili')),
                ('country', models.CharField(max_length=50, verbose_name='Mamlakati')),
                ('premiere', models.DateField(default=datetime.date.today, verbose_name='Primyerasi')),
                ('budget', models.PositiveIntegerField(default=0, help_text='Summani dollarda ko`rsating', verbose_name='Sarflangan pul')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, help_text='Summani dollarda ko`rsating', verbose_name='AQSh uchun to`lov')),
                ('fees_in_world', models.PositiveIntegerField(default=0, help_text='Summani dollarda ko`rsating', verbose_name='Dunyo uchun to`lov')),
                ('url', models.SlugField(max_length=150, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Qoralama')),
                ('actors', models.ManyToManyField(related_name='kino_aktyor', to='kinolar.actor', verbose_name='aktyorlar')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinolar.category', verbose_name='Kategoriya')),
                ('directors', models.ManyToManyField(related_name='kino_direktor', to='kinolar.actor', verbose_name='rejissorlar')),
                ('genres', models.ManyToManyField(to='kinolar.genre', verbose_name='janrlar')),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Qiymati')),
            ],
            options={
                'verbose_name': 'Reyting yulduz',
                'verbose_name_plural': 'Reyting yulduzlar',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('text', models.TextField(max_length=5000, verbose_name='Xabar')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinolar.movie', verbose_name='Kino')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinolar.review', verbose_name='OtaKlass')),
            ],
            options={
                'verbose_name': 'Komment',
                'verbose_name_plural': 'Kommentlar',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP addresi')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinolar.movie', verbose_name='Kino')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinolar.ratingstar', verbose_name='Yulduzi')),
            ],
            options={
                'verbose_name': 'Reyting',
                'verbose_name_plural': 'Reytinglar',
            },
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Poster')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinolar.movie', verbose_name='Kino')),
            ],
            options={
                'verbose_name': 'Filmdan kadr',
                'verbose_name_plural': 'Filmdan kadrlar',
            },
        ),
    ]
